# -*- coding: utf-8 -*-
"""AI Text_to_image_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYL51n8_NWhmTujw2z1zod6ALfvKnSQ6

# **Project**

---


# AI Text-to-Image Generator

---


## Project Description

---


**Title of Project: Diffusion Model-Based Text-to-Image Generator (Stable Diffusion)**

This project uses deep learning techniques, specifically diffusion models, to create an artistic or realistic image based on a text prompt that users can input, such as "a cat riding a bike in space."

It creates high-quality images from natural language input by utilising pretrained generative models, such as Stable Diffusion from Hugging Face.
## Key Features:
1. Prompt Input of User Text
Any prompt or descriptive sentence, such as "a cat sitting on a windowsill during sunset," can be entered by users.

 After interpreting this prompt, the model produces an image that is pertinent.

2. Stable Diffusion Integration makes use of the Hugging Face diffusers library's StableDiffusionPipeline.

 A potent latent text-to-image diffusion model that produces realistic-looking images is called Stable Diffusion.

3. Turning off the safety checker
To enable the creation of unrestricted outputs, the code turns off the safety checker (safety_checker=None). Although it should be used carefully, this can be significant in experimental or research settings.

4. Acceleration of Hardware
accelerates inference and generation time using GPU acceleration (torch.device("cuda")).

5. Notebook Image Rendering
The Jupyter Notebook itself shows the generated images.

 Additionally, images are saved locally.
#Use Cases:

*   Art and creative content generation
*   Game or animation concept design
*   Education and visualization
*   AI-assisted storytelling
*   Marketing and branding
"""

!pip install --upgrade diffusers transformers accelerate safetensors
!pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu118

"""**This Imports Python libraries.**"""

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image

"""**Hugging Face Authentication**"""

from huggingface_hub import login
login("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")

"""**Loading the Stable Diffusion Pipeline**"""

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_auth_token=True
).to("cuda")

"""**Generating and Displaying an Image**"""

prompt = "a futuristic cityscape at sunset, ultra-detailed, cinematic lighting"
image = pipe(prompt).images[0]
image.show()

"""**Saving the Image**"""

image.save("generated_image.png")

"""**Creating a Web Interface with Gradio**"""

!pip install gradio

import gradio as gr

def generate_image(prompt):
    image = pipe(prompt).images[0]
    return image

interface = gr.Interface(
    fn=generate_image,
    inputs=gr.Textbox(label="Enter your prompt"),
    outputs="image",
    title="Text to Image Generator",
    description="Enter a text prompt to generate an image using Stable Diffusion"
)

interface.launch()